package joining.parallel.parallelization.search;

import joining.result.ResultTuple;

import java.util.Collection;
import java.util.List;
/**
 * Execution results for search parallelization
 *
 * @author Anonymous
 */
public class SearchResult {
    /**
     * The list of results collected by a thread.
     */
    public final Collection<ResultTuple> result;
    /**
     * A list of log sentences.
     */
    public final List<String> logs;
    /**
     * The id of a thread.
     */
    public final int id;
    /**
     * Whether the result is generated by search threads.
     */
    public boolean isSearch = true;
    /**
     * Whether the result is generated by data threads.
     */
    public boolean isData = false;

    public SearchResult(Collection<ResultTuple> result, List<String> logs, int id) {
        this.result = result;
        this.logs = logs;
        this.id = id;
    }
}
